export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_UNIVERSITIES = "GET_UNIVERSITIES";
export const GET_RSOS = "GET_RSOS";
export const GET_RSOS_ADMIN = "GET_RSOS_ADMIN";
export const GET_PUBLIC_EVENTS = "GET_PUBLIC_EVENTS";
export const GET_PRIVATE_EVENTS = "GET_PRIVATE_EVENTS";
export const GET_RSO_EVENTS = "GET_RSO_EVENTS";
export const CLEAR_RSOS = "CLEAR_RSOS";
export const CLEAR_RSOS_ADMIN = "CLEAR_RSOS_ADMIN";
export const CREATE_EVENT = "CREATE_EVENT";
export const CLEAR_EVENTS = "CLEAR_EVENTS";