-- MySQL Script generated by MySQL Workbench
-- Sun Sep 22 23:51:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroku_8a8e9bdedc4afce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_8a8e9bdedc4afce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_8a8e9bdedc4afce` DEFAULT CHARACTER SET utf8 ;
USE `heroku_8a8e9bdedc4afce` ;

-- -----------------------------------------------------
-- Table `heroku_8a8e9bdedc4afce`.`universities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_8a8e9bdedc4afce`.`universities` (
  `idUniversity` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `numOfStudents` INT(11) NULL DEFAULT NULL,
  `picture` VARCHAR(45) NULL DEFAULT NULL,
  `Universities_superAdmin_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idUniversity`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `superAdmin_id_idx` (`Universities_superAdmin_id` ASC) VISIBLE,
  CONSTRAINT `Universities_superAdmin_id`
    FOREIGN KEY (`Universities_superAdmin_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_8a8e9bdedc4afce`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_8a8e9bdedc4afce`.`users` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `auth_level` INT(11) NOT NULL DEFAULT '1',
  `Users_university_id` INT(11) NOT NULL,
  `university_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `university_id_idx` (`Users_university_id` ASC) VISIBLE,
  CONSTRAINT `Users_university_id`
    FOREIGN KEY (`Users_university_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`universities` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 392
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_8a8e9bdedc4afce`.`rsos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_8a8e9bdedc4afce`.`rsos` (
  `idRSO` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `approved` INT(11) NULL DEFAULT '0',
  `RSOs_admin_id` INT(11) NOT NULL,
  `RSOs_university_id` INT(11) NOT NULL,
  PRIMARY KEY (`idRSO`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `admin_id_idx` (`RSOs_admin_id` ASC) VISIBLE,
  INDEX `university_id_idx` (`RSOs_university_id` ASC) VISIBLE,
  CONSTRAINT `RSOs_admin_id`
    FOREIGN KEY (`RSOs_admin_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RSOs_university_id`
    FOREIGN KEY (`RSOs_university_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`universities` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_8a8e9bdedc4afce`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_8a8e9bdedc4afce`.`events` (
  `idEvent` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL DEFAULT 'Meeting',
  `description` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'public',
  `rating` INT(11) NOT NULL DEFAULT '0',
  `Events_university_id` INT(11) NOT NULL,
  `Events_RSO_id` INT(11) NULL DEFAULT NULL,
  `Events_admin_id` INT(11) NOT NULL,
  `approved` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idEvent`),
  INDEX `university_id_idx` (`Events_university_id` ASC) VISIBLE,
  INDEX `RSO_id_idx` (`Events_RSO_id` ASC) VISIBLE,
  INDEX `admin_id_idx` (`Events_admin_id` ASC) VISIBLE,
  CONSTRAINT `Events_RSO_id`
    FOREIGN KEY (`Events_RSO_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`rsos` (`idRSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Events_admin_id`
    FOREIGN KEY (`Events_admin_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Events_university_id`
    FOREIGN KEY (`Events_university_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`universities` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_8a8e9bdedc4afce`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_8a8e9bdedc4afce`.`comments` (
  `idComment` INT(11) NOT NULL,
  `Comments_event_id` INT(11) NOT NULL,
  `Comments_user_id` INT(11) NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `event_id_idx` (`Comments_event_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`Comments_user_id` ASC) VISIBLE,
  CONSTRAINT `Comments_event_id`
    FOREIGN KEY (`Comments_event_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`events` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Comments_user_id`
    FOREIGN KEY (`Comments_user_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_8a8e9bdedc4afce`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_8a8e9bdedc4afce`.`ratings` (
  `idRating` INT(11) NOT NULL,
  `Ratings_event_id` INT(11) NOT NULL,
  `Ratings_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`idRating`),
  INDEX `event_id_idx` (`Ratings_event_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`Ratings_user_id` ASC) VISIBLE,
  CONSTRAINT `Ratings_event_id`
    FOREIGN KEY (`Ratings_event_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`events` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ratings_user_id`
    FOREIGN KEY (`Ratings_user_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_8a8e9bdedc4afce`.`rso_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_8a8e9bdedc4afce`.`rso_members` (
  `idRSO_Member` INT(11) NOT NULL AUTO_INCREMENT,
  `RSO_Member_user_id` INT(11) NOT NULL,
  `RSO_Member_RSO_id` INT(11) NOT NULL,
  PRIMARY KEY (`idRSO_Member`),
  INDEX `user_id_idx` (`RSO_Member_user_id` ASC) VISIBLE,
  INDEX `RSO_id_idx` (`RSO_Member_RSO_id` ASC) VISIBLE,
  CONSTRAINT `RSO_Member_RSO_id`
    FOREIGN KEY (`RSO_Member_RSO_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`rsos` (`idRSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`RSO_Member_user_id`)
    REFERENCES `heroku_8a8e9bdedc4afce`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
